Running from arcus-10
2019-05-15 06:51:30.215726: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-15 06:51:33.012157: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties: 
name: TITAN V major: 7 minor: 0 memoryClockRate(GHz): 1.455
pciBusID: 0000:83:00.0
totalMemory: 11.75GiB freeMemory: 11.34GiB
2019-05-15 06:51:33.012226: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2019-05-15 06:51:33.470334: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-15 06:51:33.470378: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 
2019-05-15 06:51:33.470384: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N 
2019-05-15 06:51:33.470677: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10955 MB memory) -> physical GPU (device: 0, name: TITAN V, pci bus id: 0000:83:00.0, compute capability: 7.0)
{'alpha': 0.8349273260918855, 'dropout': 0.20537494105704618, 'lr': 0.0001858625732530178, 'leaky_relu': 0.42484253338570127, 'batch_norm': 1, 'num_layers': 6, 'layer_0': 430, 'layer_1': 116, 'layer_2': 146, 'layer_3': 443, 'layer_4': 387, 'layer_5': 244, 'layer_6': 433, 'layer_7': 217, 'max_concurrent': 3, 'P': 'arcus_gpu.p', 'q': 'arcus.q', 'l': "hostname='(arcus-1|arcus-2|arcus-3|arcus-4|arcus-5|arcus-6|arcus-7|arcus-8|arcus-9|arcus-10)'", 'env': '/home/jott1/Projects/SHERPA_EX/.profile', 'data': 'fluxbypass_aqua', 'net_type': 'conservation', 'loss_type': 'mse', 'batch_size': 2048, 'data_dir': '/baldig/chemistry/earth_system_science/', 'max_dense_layers': 8, 'epochs': 25, 'patience': 10}
Epoch 1/25
 - 2869s - loss: 661.2191 - mean_squared_error: 661.2191 - val_loss: 324.8842 - val_mean_squared_error: 324.8842
Epoch 2/25
 - 668s - loss: 330.1653 - mean_squared_error: 330.1653 - val_loss: 343.8869 - val_mean_squared_error: 343.8869
Epoch 3/25
 - 3708s - loss: 318.9183 - mean_squared_error: 318.9183 - val_loss: 357.6098 - val_mean_squared_error: 357.6098
Epoch 4/25
 - 695s - loss: 313.4510 - mean_squared_error: 313.4510 - val_loss: 353.2949 - val_mean_squared_error: 353.2949
Epoch 5/25
 - 674s - loss: 309.9409 - mean_squared_error: 309.9409 - val_loss: 338.4537 - val_mean_squared_error: 338.4537
Epoch 6/25
 - 674s - loss: 307.6072 - mean_squared_error: 307.6072 - val_loss: 368.4528 - val_mean_squared_error: 368.4528
Epoch 7/25
 - 685s - loss: 305.8567 - mean_squared_error: 305.8567 - val_loss: 351.2395 - val_mean_squared_error: 351.2395
Epoch 8/25
 - 661s - loss: 304.4854 - mean_squared_error: 304.4854 - val_loss: 330.8216 - val_mean_squared_error: 330.8216
Epoch 9/25
 - 686s - loss: 303.4453 - mean_squared_error: 303.4453 - val_loss: 342.1032 - val_mean_squared_error: 342.1032
Epoch 10/25
 - 681s - loss: 302.6104 - mean_squared_error: 302.6104 - val_loss: 335.5003 - val_mean_squared_error: 335.5003
Epoch 11/25
 - 674s - loss: 301.8853 - mean_squared_error: 301.8853 - val_loss: 355.6130 - val_mean_squared_error: 355.6130
/pkg/python/3.6.1-centos7/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Done with trial 5
