Running from arcus-10
2019-05-17 03:35:41.471446: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-17 03:35:44.405318: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties: 
name: TITAN V major: 7 minor: 0 memoryClockRate(GHz): 1.455
pciBusID: 0000:02:00.0
totalMemory: 11.75GiB freeMemory: 11.34GiB
2019-05-17 03:35:44.405396: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2019-05-17 03:35:44.920164: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-17 03:35:44.920215: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 
2019-05-17 03:35:44.920223: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N 
2019-05-17 03:35:44.920580: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10955 MB memory) -> physical GPU (device: 0, name: TITAN V, pci bus id: 0000:02:00.0, compute capability: 7.0)
Epoch 1/25
 - 2740s - loss: 531.3674 - mean_squared_error: 531.3674 - val_loss: 453.4857 - val_mean_squared_error: 453.4857
Epoch 2/25
 - 606s - loss: 458.9439 - mean_squared_error: 458.9439 - val_loss: 417.8269 - val_mean_squared_error: 417.8269
Epoch 3/25
 - 601s - loss: 454.2955 - mean_squared_error: 454.2955 - val_loss: 450.9659 - val_mean_squared_error: 450.9659
Epoch 4/25
 - 600s - loss: 452.0819 - mean_squared_error: 452.0819 - val_loss: 422.7606 - val_mean_squared_error: 422.7606
Epoch 5/25
 - 594s - loss: 450.6274 - mean_squared_error: 450.6274 - val_loss: 419.6263 - val_mean_squared_error: 419.6263
Epoch 6/25
 - 601s - loss: 449.8563 - mean_squared_error: 449.8563 - val_loss: 426.7157 - val_mean_squared_error: 426.7157
Epoch 7/25
 - 596s - loss: 449.1764 - mean_squared_error: 449.1764 - val_loss: 403.4486 - val_mean_squared_error: 403.4486
Epoch 8/25
 - 594s - loss: 448.8411 - mean_squared_error: 448.8411 - val_loss: 439.2128 - val_mean_squared_error: 439.2128
Epoch 9/25
 - 600s - loss: 448.3624 - mean_squared_error: 448.3624 - val_loss: 461.2282 - val_mean_squared_error: 461.2282
Epoch 10/25
 - 2536s - loss: 448.2075 - mean_squared_error: 448.2075 - val_loss: 446.0353 - val_mean_squared_error: 446.0353
Epoch 11/25
 - 673s - loss: 447.8387 - mean_squared_error: 447.8387 - val_loss: 430.9864 - val_mean_squared_error: 430.9864
Epoch 12/25
 - 609s - loss: 447.5851 - mean_squared_error: 447.5851 - val_loss: 488.7071 - val_mean_squared_error: 488.7071
Epoch 13/25
 - 586s - loss: 447.3144 - mean_squared_error: 447.3144 - val_loss: 432.9616 - val_mean_squared_error: 432.9616
Epoch 14/25
 - 593s - loss: 447.1508 - mean_squared_error: 447.1508 - val_loss: 462.8541 - val_mean_squared_error: 462.8541
Epoch 15/25
 - 606s - loss: 447.1415 - mean_squared_error: 447.1415 - val_loss: 470.2070 - val_mean_squared_error: 470.2070
Epoch 16/25
 - 593s - loss: 446.8586 - mean_squared_error: 446.8586 - val_loss: 455.1428 - val_mean_squared_error: 455.1428
Epoch 17/25
 - 595s - loss: 446.9865 - mean_squared_error: 446.9865 - val_loss: 449.1243 - val_mean_squared_error: 449.1243
/pkg/python/3.6.1-centos7/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Done with trial 15
