2019-05-18 23:54:52.659461: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-18 23:54:52.844531: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties: 
name: GeForce GTX TITAN X major: 5 minor: 2 memoryClockRate(GHz): 1.076
pciBusID: 0000:83:00.0
totalMemory: 11.93GiB freeMemory: 11.23GiB
2019-05-18 23:54:52.844579: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2019-05-18 23:54:53.384532: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-18 23:54:53.384587: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 
2019-05-18 23:54:53.384597: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N 
2019-05-18 23:54:53.384970: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10865 MB memory) -> physical GPU (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:83:00.0, compute capability: 5.2)
/pkg/python/3.6.1-centos7/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Generator will have 71163904 samples in 34748 batches
Features have shape 94; targets have shape 65
Generator will have 72343552 samples in 35324 batches
Features have shape 94; targets have shape 65
Traceback (most recent call last):
  File "main.py", line 101, in <module>
    net.save()
  File "/home/jott1/Projects/CBRAIN-CAM/notebooks/tbeucler_devlog/hp_opt_conservation/model.py", line 151, in save
    self.model.save(file_name+'.h5')
  File "/home/jott1/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1278, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/home/jott1/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/saving.py", line 89, in save_model
    f = h5py.File(filepath, mode='w')
  File "/pkg/python/3.6.1-centos7/lib/python3.6/site-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/pkg/python/3.6.1-centos7/lib/python3.6/site-packages/h5py/_hl/files.py", line 107, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-s_7obrrg-build/h5py/_objects.c:2840)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-s_7obrrg-build/h5py/_objects.c:2798)
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create (/tmp/pip-s_7obrrg-build/h5py/h5f.c:2284)
OSError: Unable to create file (Unable to open file: name = 'sherparesults/8col_random/normal_mse/models/00045.h5', errno = 2, error message = 'no such file or directory', flags = 13, o_flags = 242)
